CREATE TABLE `llm_models` (
	`id` text PRIMARY KEY NOT NULL,
	`provider` text NOT NULL,
	`model_name` text NOT NULL,
	`display_name` text NOT NULL,
	`api_endpoint` text NOT NULL,
	`api_version` text,
	`context_window` integer NOT NULL,
	`max_output_tokens` integer NOT NULL,
	`supports_streaming` integer DEFAULT true NOT NULL,
	`supports_functions` integer DEFAULT false NOT NULL,
	`supports_vision` integer DEFAULT false NOT NULL,
	`input_price_per_1m` integer NOT NULL,
	`output_price_per_1m` integer NOT NULL,
	`release_date` integer,
	`deprecated` integer DEFAULT false NOT NULL,
	`deprecation_date` integer,
	`replacement_model_id` text,
	`recommended_temperature` integer,
	`recommended_top_p` integer,
	`tags` text,
	`description` text,
	`status` text DEFAULT 'active' NOT NULL,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	`updated_at` integer DEFAULT (unixepoch()) NOT NULL
);
--> statement-breakpoint
CREATE TABLE `model_usage` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`user_model_config_id` text,
	`model_id` text NOT NULL,
	`request_type` text NOT NULL,
	`input_tokens` integer NOT NULL,
	`output_tokens` integer NOT NULL,
	`total_tokens` integer NOT NULL,
	`input_cost_usd` integer NOT NULL,
	`output_cost_usd` integer NOT NULL,
	`total_cost_usd` integer NOT NULL,
	`latency_ms` integer,
	`success` integer NOT NULL,
	`error_message` text,
	`metadata` text,
	`timestamp` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`user_model_config_id`) REFERENCES `user_model_configs`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`model_id`) REFERENCES `llm_models`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `system_config` (
	`id` text PRIMARY KEY NOT NULL,
	`system_user_id` text,
	`default_benchmark_model_id` text,
	`default_judge_model_id` text,
	`global_rate_limit` integer DEFAULT 10000 NOT NULL,
	`per_user_rate_limit` integer DEFAULT 1000 NOT NULL,
	`features` text,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	`updated_at` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (`system_user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`default_benchmark_model_id`) REFERENCES `llm_models`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`default_judge_model_id`) REFERENCES `llm_models`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `user_model_configs` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`model_id` text NOT NULL,
	`api_key` text NOT NULL,
	`api_key_last_four` text NOT NULL,
	`custom_temperature` integer,
	`custom_max_tokens` integer,
	`custom_system_prompt` text,
	`monthly_budget_usd` integer,
	`daily_request_limit` integer,
	`enabled` integer DEFAULT true NOT NULL,
	`nickname` text,
	`notes` text,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	`updated_at` integer DEFAULT (unixepoch()) NOT NULL,
	`last_used_at` integer,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`model_id`) REFERENCES `llm_models`(`id`) ON UPDATE no action ON DELETE cascade
);
